spring:
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017/?replicaSet=rs0&directConnection=true
            database: football
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
