server:
    port: 8082
management:
  endpoints:
    web:
      exposure:
        include: bindings, health, info, metrics, env, beans, loggers
spring:
  application:
    name: timeline

  rabbitmq:
    host: localhost
    username: packt
    password: packt
    port: 5672