logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  cloud:
    azure:
# Properties like spring.cloud.azure.credential.client-id are global properties.
# Properties like spring.cloud.azure.active-directory.credential.client-id are Microsoft Entra ID properties.
# If Microsoft Entra ID properties is not configured, global properties will be used.
#      credential:
#        client-id:
#        client-secret:
#      profile:
#        tenant-id:
      active-directory:
        b2c:
          enabled: true
          profile:
            tenant-id: b2b8f451-385b-4b9d-9268-244a8f05b32f
          credential:
            client-id: fdc345e8-d545-49af-aa1a-04a087364c8b
          base-uri: https://sb3cookbook.b2clogin.com             # Such as: https://xxxxb2c.b2clogin.com
          user-flows:
            sign-up-or-sign-in: B2C_1_SISU