CREATE DATABASE football
    WITH
    OWNER = packtd
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

\c football

-- CREATE TABLE IF NOT EXISTS albums
-- (
--     id integer GENERATED BY DEFAULT AS IDENTITY,
--     expire_date date,
--     description character varying(255),    
--     title character varying(255) NOT NULL,
--     CONSTRAINT albums_pkey PRIMARY KEY (id)
-- );

CREATE TABLE IF NOT EXISTS teams
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255),
    CONSTRAINT teams_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS players
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    jersey_number integer,    
    name character varying(255),
    position character varying(255),
    date_of_birth date,
    team_id integer,
    CONSTRAINT players_pkey PRIMARY KEY (id),
    CONSTRAINT fk_players_teams FOREIGN KEY (team_id)
        REFERENCES teams (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
);

-- CREATE TABLE IF NOT EXISTS cards
-- (
--     id integer GENERATED BY DEFAULT AS IDENTITY,
--     player_id integer NOT NULL,
--     CONSTRAINT cards_pkey PRIMARY KEY (id),
--     CONSTRAINT players_fk FOREIGN KEY (player_id)
--         REFERENCES players (id) MATCH SIMPLE
--         ON UPDATE NO ACTION
--         ON DELETE NO ACTION
-- );

-- CREATE TABLE IF NOT EXISTS cardholders
-- (
--     album_id integer NOT NULL,
--     card_id integer,
--     player_id integer NOT NULL,
--     CONSTRAINT cardholders_pkey PRIMARY KEY (album_id, player_id),
--     CONSTRAINT albums_fk FOREIGN KEY (album_id)
--         REFERENCES albums (id) MATCH SIMPLE
--         ON UPDATE NO ACTION
--         ON DELETE NO ACTION,
--     CONSTRAINT cards_fk FOREIGN KEY (card_id)
--         REFERENCES cards (id) MATCH SIMPLE
--         ON UPDATE NO ACTION
--         ON DELETE NO ACTION
-- );