
server:
  port: 0

spring:
  application:
    name: football-api
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
          - football
          - football-ui
          issuer-uri: http://localhost:9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
