server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: bindings, health, info, metrics, env, beans, loggers
spring:
  application:
    name: ranking
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/football
    username: packt
    password: packt

  rabbitmq:
    host: localhost
    username: packt
    password: packt
    port: 5672

  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
              bindingRoutingKey: football.goal.#
      function:
        routing: enabled
        bindings:
          processGoals-in-0: input
        routing-expression: headers['eventType']
      bindings:
        input:
          destination: match-events-topic
          group: ranking
          bindingRoutingKey: football.goal.#
          exchangeType: direct
          binder: rabbit

