spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        open-in-view: false
    datasource:
        url: jdbc:postgresql://localhost:5432/football
        username: packt
        password: packt