spring:
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017/?directConnection=true
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
