management:
    endpoint:
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,env,metrics,beans,loggers,football
football:
    folder: teams
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/football
        username: packtd
        password: packtd

