server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: bindings, health, info, metrics, env, beans, loggers
spring:
  application:
    name: timeline
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/football
    username: packt
    password: packt

  rabbitmq:
    host: localhost
    username: packt
    password: packt
    port: 5672

  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
      function:
        bindings:
          processMatchEvent-in-0: input
      bindings:
        input:
          destination: match-events-topic
          group: timeline
