server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: bindings, health, info, metrics, env, beans, loggers
spring:
  application:
    name: score

  rabbitmq:
    host: localhost
    username: packt
    password: packt
    port: 5672

  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: football.goal.#
              autoBindDlq: true
              maxAttempts: 3
              ttl: 1000

      function:
        bindings:
          processGoals-in-0: input
      bindings:
        input:
          destination: match-events-topic
          group: score

