management:
    endpoint:
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,env,metrics,beans,loggers,football
    tracing:
        sampling:
            probability: 1.0            
football:
    folder: teams
spring:
    application:
        name: trading-service
    datasource:
        url: jdbc:postgresql://localhost:5432/football
        username: packtd
        password: packtd

