management:
    endpoints:        
        # jmx:
        #     exposure:
        #         include: env,health,metrics,beans,loggers
        web:
            exposure:
                include: health,env,metrics,beans,loggers,httptrace
    trace:
        http:
            enabled: true
spring:
    application:
        name: football
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL82Dialect
        open-in-view: false
        show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/football
        username: packt
        password: packt
        initialization-mode: embedded
        hikari:
            maximum-pool-size: 4
    data:
        cassandra:
            keyspace-name: footballKeyspace
            schema-action: CREATE_IF_NOT_EXISTS
            contact-points: localhost
            local-datacenter: datacenter1
            session-name: cassandraSession
            port: 9042