global:
  scrape_interval: 3s
scrape_configs:
  - job_name: 'football_trading_app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['football:8080']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgresexporter:9187']
