version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: packt
      MONGO_INITDB_ROOT_PASSWORD: packt
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: packt
      ME_CONFIG_MONGODB_ADMINPASSWORD: packt
      ME_CONFIG_MONGODB_URL: mongodb://packt:packt@mongo:27017/