version: '3.7'
include:
  - docker-compose-redis.yml
services:
  football:
    image: football:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/football
      - spring.data.redis.host=redis